name: Docker

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: build

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      
      
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends qemu-user-static binfmt-support qemu-system-arm
          sudo update-binfmts --enable qemu-arm
          sudo update-binfmts --enable qemu-aarch64
          sudo update-binfmts --display qemu-arm
          sudo update-binfmts --display qemu-aarch64
          cp /usr/bin/qemu-arm-static $(pwd)
          cp /usr/bin/qemu-aarch64-static $(pwd)

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/electron/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
